use_frameworks!
source 'https://github.com/dortus47/SSLog.git'

platform :ios, '9.0'

target 'SSLog_Example' do
  pod 'SSLog', :path => '../'

  target 'SSLog_Tests' do
    inherit! :search_paths

    
  end
end
